language: objective-c
before_install:
  - export LANG=en_US.UTF-8
  - gem install cocoapods xcpretty slather -N
  - pod install
  
script:
  - set -o pipefail && xcodebuild test -workspace SWTableViewCell.xcworkspace -scheme SWTableViewCell -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c

after_success: slather
